services:
  mongodb:
    image: mongo:8
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: betor
      MONGO_INITDB_ROOT_PASSWORD: betor
    healthcheck:
      test:
        - CMD
        - echo
        - 'db.runCommand("ping").ok'
        - "|"
        - mongosh
        - localhost:27017/test
        - --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express:1
    ports:
    - 8081:8081
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: betor
      ME_CONFIG_MONGODB_ADMINPASSWORD: betor
      ME_CONFIG_MONGODB_URL: mongodb://betor:betor@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:8
    ports:
    - 6379:6379
